### ISSUE TITLE
Refactor Implementation to Replace Reflect API with SQLX for Improved Performance and Maintainability

### ISSUE THREAD

**Issue by RAVAN0407** [techrail/bark#4]
The current implementation of the project relies on the use of the Reflect API, which is considered suboptimal due to its impact on performance and maintainability. To enhance the overall codebase, this issue proposes refactoring the existing code to replace the Reflect API with SQLX, a more efficient and structurally sound approach that offers significant improvements in terms of both performance and code maintainability.

**Comment by vaibhav-kaushal** [comment]
I think this has been done, right? @RAVAN0407

**Comment by RAVAN0407** [comment]
yes!
The reflect package is removed and the db tags are added for the structure by @deepto98
