### ISSUE TITLE
Add function to allow user to set json in more_data while logging

### ISSUE THREAD

**Issue by bhagatvansh** [techrail/bark#44]
The MoreData member of BarkLog takes a json as value. We need to create a functionality to allow user to set this to any value of the user's choice. By default, this will be empty.

Something like: 
more_data: 
{
errorFileName: "",
errorFunctionName:"",
errorLine: 
}

Or anything relevant to the user's code base this is just a random example.

**Comment by vaibhav-kaushal** [comment]
This has been implemented in the client using the `Config.Raw` function.
