### ISSUE TITLE
Writing logs to plain text file

### ISSUE THREAD

**Issue by bhagatvansh** [techrail/bark#45]
Default flow of bark after collecting logs is to send it to send to app_log table. However, if the user requires the logs to be written to a file, they should be able to configure it. 

Using a simple variable while creating logger, we can ask the user input. WriteToDB ? Yes/No. 

If it is no, then the logs after being sent to the channel, will be written to a .txt file.

**Comment by vaibhav-kaushal** [comment]
This was done earlier when @itishrishikesh finished the client. It has been revised with documentation in #82.
