### ISSUE TITLE
FEAT : Add webhook support to bark client

### ISSUE THREAD

**Issue by y0tik** [techrail/bark#50]
**NOTE**: A new issue (#67) was created to better capture the needs according to the existing structure.

Just like we have `.error .info .warn`, we can also have a `.webhook` that will insert a log to the database and also call the webhook url with that log. You can find more information about webhooks [here](https://zapier.com/apps/webhook/integrations)

These can be used when a critical part of your application fails. Instead of just logging to the database, you can also call a webhook to notify you immediately or run an automation.

The function may look something like this:

```jsx
func (c *Config) Webhook(webhookURL, logMsg string) {
	// ..logic
}
```

**Comment by npmaile** [comment]
I'm taking a shot at this one. I'll probably have it ready for a draft pr in about 2 days. my fork: https://github.com/npmaile/bark/tree/webhook
