### ISSUE TITLE
Benchmarking the SQL connectors

### ISSUE THREAD

**Issue by vaibhav-kaushal** [techrail/bark#7]
In the world of PostgreSQL, we have two very famous connectors: 

1. [pq](https://github.com/lib/pq) - which is used by the famous [sqlx](https://github.com/jmoiron/sqlx) library by default.
2. [pgx](https://github.com/jackc/pgx) - which is also pretty famous and it is famous for being ***fast***! 

Now, bark is supposed to be ***fast***. So we need to know which one is fast and by what margin. There are other questions around PostgreSQL connections, pooling, support for goroutines, error handling etc. but for now we need to just check the performance difference between the two libraries!

**Comment by RAVAN0407** [comment]
```
This package is currently in maintenance mode, which means:

It generally does not accept new features.
It does accept bug fixes and version compatability changes provided by the community.
Maintainers usually do not resolve reported issues.
Community members are encouraged to help each other with reported issues.
For users that require new features or reliable resolution of reported bugs, we recommend using [pgx](https://github.com/jackc/pgx) which is under active development.
```
This is the status of `pq` package.

**Comment by RAVAN0407** [comment]
![image](https://github.com/techrail/bark/assets/72258505/7011cd6a-d49c-449c-8d14-7748b9aff3f4)

This is the benchmark score for a simple query using pgx

**Comment by RAVAN0407** [comment]
@vaibhav-kaushal  will the benchmark scores differ from machine to machine?

**Comment by deepto98** [comment]
These are the results I got for sqlx:
![image](https://github.com/techrail/bark/assets/91651033/fc345187-04c9-4794-b61f-9df7eb278781)

**Comment by RAVAN0407** [comment]
@deepto98  
I'm unable to run the tests, Can you check if there are any missing files in the repo

**Comment by vaibhav-kaushal** [comment]
We have already moved to pgx
