### ISSUE TITLE
Unable to import into other projects

### ISSUE THREAD

**Issue by itishrishikesh** [techrail/bark#8]
**Problem:** Right now Bark exposes a simple HTTP endpoint to insert data into the database, but doesn't have a package that can be imported into another project to be used directly.

**Proposed behavior:**  To include a package `logger` which exposes a method `GetLogger`, which can be used to obtain a logger function that can be readily used in other projects just by importing the logger package.

Example:

```
log:= logger.GetLogger(serviceName)
```
Then `log` is used like this,
```
bark(INT_LEVEL, "code", "message",  some_json_data)
```

**Comment by vaibhav-kaushal** [comment]
It was fixed in #9
